"""Extract the Metro-North infrastructure inside this world's bounds.

Input: the ZIP linked at https://www.mta.info/developers (gtfsmnr.zip).
Uses GTFS shapes/stops only; runtime timetables and elevations are synthetic.
Run: python tools/import-metro-north.py /path/to/gtfsmnr.zip
"""
import csv
import hashlib
import io
import json
import pathlib
import sys
import zipfile
from collections import defaultdict

archive = pathlib.Path(sys.argv[1])
with zipfile.ZipFile(archive) as feed:
    def rows(name):
        return list(csv.DictReader(io.TextIOWrapper(feed.open(name), encoding='utf-8-sig')))

    shapes = defaultdict(list)
    for row in rows('shapes.txt'):
        shapes[row['shape_id']].append((int(row['shape_pt_sequence']), float(row['shape_pt_lon']), float(row['shape_pt_lat'])))
    # Select the most detailed inbound shape ending at Grand Central for each
    # main line. IDs can change between feeds; route names and stop IDs are data.
    routes = {r['route_long_name']: r['route_id'] for r in rows('routes.txt')}
    trips = rows('trips.txt')
    def line(name):
        ids = {t['shape_id'] for t in trips if t['route_id'] == routes[name] and t['direction_id'] == '1'}
        candidates = []
        for key in ids:
            points = [list(p[1:]) for p in sorted(shapes[key], reverse=True)]
            if abs(points[0][0] + 73.97738) < .001 and abs(points[0][1] - 40.75315) < .001:
                candidates.append(points)
        return max(candidates, key=len)

    hudson, harlem = line('Hudson'), line('Harlem')
    shared = 0
    while shared < min(len(hudson), len(harlem)) and hudson[shared] == harlem[shared]:
        shared += 1
    if shared < 100 or not 40.81 < hudson[shared-1][1] < 40.83:
        raise ValueError('Cannot identify the shared Park Avenue trunk and Mott Haven junction')

    def clip(points):
        # Include one tile of continuation beyond the mapped city, so trains
        # disappear outside view instead of ending abruptly at a boundary stop.
        result = []
        for point in points:
            result.append(point)
            if point[1] > 40.887 or point[0] > -73.897:
                break
        return result

    stops = {r['stop_id']: {'id': r['stop_id'], 'name': r['stop_name'],
                           'lon': float(r['stop_lon']), 'lat': float(r['stop_lat'])}
             for r in rows('stops.txt')}
    data = {
        'source': 'https://rrgtfsfeeds.s3.amazonaws.com/gtfsmnr.zip',
        'sha256': hashlib.sha256(archive.read_bytes()).hexdigest(),
        'trunk': hudson[:shared],
        'hudson': clip(hudson[shared-1:]),
        'harlem': clip(harlem[shared-1:]),
        'stations': {k: stops[k] for k in ['1', '4', '622', '9', '10', '11', '14', '54', '55']},
    }
target = pathlib.Path(__file__).resolve().parents[1] / 'web/static/world/assets/rail/metro-north-data.js'
target.write_text('// Generated by tools/import-metro-north.py from MTA GTFS shapes and stops.\n'
                  '// Coordinates are WGS84 [longitude, latitude]; no live service data.\n'
                  'export const metroNorthData = ' + json.dumps(data, separators=(',', ':')) + ';\n')
print(f'Wrote {target}: {shared} trunk points, {len(data["hudson"])} Hudson and {len(data["harlem"])} Harlem branch points, {len(data["stations"])} stations')
