/** Regenerate the small city-wide footprint index from the vendored OSM tiles. */
import { readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { gunzipSync } from 'node:zlib';
import { fileURLToPath } from 'node:url';
const root = fileURLToPath(new URL('../', import.meta.url));
const roads = new Map();
for (const name of readdirSync(root + 'public/world/world/tiles').sort()) {
  if (!name.endsWith('.json.gz')) continue;
  const tile = JSON.parse(gunzipSync(readFileSync(root + 'public/world/world/tiles/' + name)));
  for (const r of tile.roads ?? []) if (r.tunnel && !['footway', 'pedestrian', 'steps', 'cycleway'].includes(r.cls)) {
    roads.set(r.id, { width: r.width, pts: r.pts });
  }
}
const code = '// Generated by tools/index-tunnels.mjs; do not edit.\nexport const tunnelRoads = ' + JSON.stringify([...roads.values()]) + ';\n';
writeFileSync(root + 'src/client/src/buildings/tunnel-roads.js', code);
writeFileSync(root + 'public/world/assets/tunnel-roads.js', code);
console.log(`Indexed ${roads.size} vehicular tunnels.`);
